server:
  port: 8080
  servlet:
    context-path: /project1
logging:
  level:
    root: info
    org.zhouhy.springboot.project1: warn
  file:
    name: logs/system.log
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true